messages:
  purchase: "You purchased a &e&l%s&f for &a%d$"
  after-purchase-cash: "You now have &a%d$"
  cant-afford: "&cYou cant afford &n%s&f ( &a%d$ &f/ &c%d$ &f)"
  gun-not-exist: "&c'%s' does not exist. Do '/buy list' to list all guns."
  gun-list-start: "===== &b&lGUN LIST&f ====="
  gun-list-format: "&a%4d$&f &e%s&f | %s"
  gun-list-end:   "-> You have &a%d$"
  cash: "You have &a%d$"

guns:
  glock:
    name: Glock
    item-display-name: "&r&7Glock"
    description: a pistol
    aliases: ["glock", "pistol"]
    item-material: STONE_HOE
    cost: 100

    full-auto: false
    full-auto-charge: 5
    shoot-tick-interval: 6

    projectile-count: 1
    gravity: true
    projectile-y-bias: 3

    velocity: 4.0
    damage: 1.0
    knockback: 1
    pierce: 1

    base-accruacy: 6.0
    sneek-accruacy-modifier: -6.0
    accruacy-heat-effect: 1.0
    heat-add: 12.0
    heat-sub: 1.0
    heat-max: 20.0

    sound: ENTITY_ARROW_SHOOT
    sound-volume: 1.0 # 0 - 1
    sound-pitch: 1.0 # 0 - 1
